# This file contains the required dependencies to fully execute all Jupyter notebooks and tutorials contained in this repository. 
# 
# To create this conda environment for the first time:
#   run from your commandline:  conda env create --file environment.yml
# ----------
# To initialize this environment in conda:
#   run from your commandline:  conda activate tropess-env
name: tropess-env
channels:
 - conda-forge
dependencies:
 - python>=3.9
 - nb_conda 
 - numpy
 - earthaccess
 - requests
 - s3fs
 - xarray
 - netCDF4
 - h5netcdf
 - pandas
 - pathlib
 - matplotlib
 - matplotlib
 - scipy
 - cartopy
 - imageio
 - Basemap
 - numpy
 - pip 
 - pip:
# works for regular pip packages
   - podaac-data-subscriber

# Python standard library dependencies
# - jupyter
# - contextlib
# - datetime
# - optparse
# - h5netcdf
