# run: conda env create --file environment.yml
name: tropess-env
channels:
 - conda-forge
dependencies:
 - python>=3.9
 - anaconda
 - numpy
 - earthaccess
 - requests
 - s3fs
 - xarray
 - netCDF4
 - h5netcdf
 - pandas
 - pathlib
 - matplotlib
 - matplotlib
 - scipy
 - cartopy
 - imageio
 - Basemap
 - numpy
 - pip 
 - pip:
# works for regular pip packages
   - podaac-data-subscriber

# Python standard library dependencies
# - jupyter
# - contextlib
# - datetime
# - optparse
# - h5netcdf
